spring:
  datasource:
    url: jdbc:sqlserver://5.135.244.239:1433;databaseName=ms-declaration-impots;encrypt=false
    username: sa
    password: YourStrong!Passw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
providers:
  data:
    endpoint: http://localhost:8000
  mails:
    endpoint: https://mails.dev.chillo.fr

